apiVersion: apps/v1
kind: Deployment
metadata:
  name: nike-app
  labels:
    app: nike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nike
  template:
    metadata:
      labels:
        app: nike
    spec:
      containers:
      - name: nike
        image: sha256:276512e26cae29ba51662ffeb67174be40b2a57ccba1b78403e4ff0ff1bf35e4 # Update with your Docker Hub image
        ports:
        - containerPort: 8087