apiVersion: apps/v1
kind: Deployment
metadata:
  name: nike-app
  labels:
    app: nike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nike
  template:
    metadata:
      labels:
        app: nike
    spec:
      containers:
      - name: nike
        image: sha256:f4b18d6388a787688ece48e44daa80927fcb743e28fda2b9faa2f7538fd44cef # Update with your Docker Hub image
        ports:
        - containerPort: 8087